sni/lmd

lmd/prometheus.go

I would structure the metrics (in the end, their names don't change anyway) like discussed in https://github.com/prometheus/docs/issues/82

use namespace and subsystem in metric names

---

lmd/peer.go

Minor changes.
Stop the ticker on shutdown so it won't leak.
Remove the outer for loop that appears to be obsolete.

Peer update loop: Stop ticker and remove outer loop

---

lmd/peer.go

Hello,
in https://github.com/sni/lmd/blob/master/lmd/peer.go#L1476, you use the number of status in the result to determine if it is a LMD backend.
shinken return one line per scheduler. As a result, in a HA configuration, it is wrongly flagged as a LMD backend.
Putting test for LMD backend at the end of the if else chain solve the issue.

shinken backend detected as LMD backend

---

lmd/request.go

Livestatus accepts Limit:0. LMD throws error, though it can be neglected. This fix addresses this.

Add support for Limit:0 filter

---

lmd/request.go

Livestatus supports columnHeaders as request parameter.
LMD has an internal option "sendcolumnheader" which can extend this.

Add support for columnheaders

---

lmd/filter.go

And/Or are used to combine filters.
LMD throws error with a value 0.
However livestatus accepts a value of 0, which is internally discarded though.
This fix addresses this issue.

Add support for And/Or: 0 

---

lmd/request.go

Though not documented, livestatus accepts value of 0 with StatsAnd.
"StatsAnd:0" gives a result equivalent to "Stats: state != 9999" which is
kind of dummy to retrieve count of host/service in all states.

Add support for StatsAnd/Or:0

---

lmd/request.go

Livestatus accepts and modifies it's output time based on received 'Localtime' parameter.
Since LMD works on unix timestamps only, hence ignoring this parameter if received.

Ignore Localtime parameter

---

lmd/objects.go

Correct regression on shinken backend introduced by https://github.com/sni/lmd/commit/0458719aa69eda4e008e990b96ee12bb8acea0a7
```
[2018-07-27 13:13:24][Error][peer.go:2397] [Monitoring Site A] Panic: runtime error: index out of range
[2018-07-27 13:13:24][Error][peer.go:2398] [Monitoring Site A] goroutine 20 [running]:
runtime/debug.Stack(0xc42019e000, 0x8fa3bf, 0xe)
/usr/lib/golang/src/runtime/debug/stack.go:24 +0xa7
main.logPanicExitPeer(0xc4202400c0)
/home/a2683/cvs/lmd-nrd/lmd/peer.go:2398 +0x12f
panic(0x874900, 0xb5e030)
/usr/lib/golang/src/runtime/panic.go:491 +0x283
main.(*Peer).UpdateDeltaTableServices(0xc4202400c0, 0xc42031e160, 0xa6, 0x0, 0x0)
/home/a2683/cvs/lmd-nrd/lmd/peer.go:798 +0x1027
main.(*Peer).UpdateDeltaTableFullScan(0xc4202400c0, 0xc4201d55f0, 0xc42001e940, 0x40, …
```

Offset row id by other backend optional fields

---

lmd/peer.go

If there is an error while building table, lock isn't released and
LMD hang.

Release lock

---

lmd/peer.go

This pull request adds a field called `ColumnsMap` to the DataTable object that is used by peers during initialization. This field is a map of type `map[int]int`, and it maps a ColumnIndex (as described by the Table, such as the numbers you find in `Table.ColumnIndexes` or in `Column.Index`, to the actual index to access when extracting data from rows in the DataTable data (`DataTable.Data`).
As explained in #41, this is a required step to avoid offsetting errors, because if the table has optional fields that are not present for a peer of a particular kind, each row in the datatable will have less columns than the sum of static and dynamic columns defined in the Table object backing that particular datatable.
If a column that has an index greater than the index of an optional column that …

Make peers aware of the columns for the DataTables

---

lmd/http.go
lmd/peer.go
lmd/request.go
lmd/request_test.go
lmd/response.go

Livestatus respond to a query with 'Limit: 0', by providing all the
columns for the object type, but no actual objects.
Before this commit, LMD would ignore Limit: 0 and return all the found
objects.
This commit ensures that setting Limit: 0, results in LMD
responding only with the object type columns.

Do not ignore Limit: 0

---

lmd/request.go

Requests that don't use colon followed by exactly one space in a request header
line are not recognized. This commit makes the parser more forgiving of spacing
in the request header and command lines, making it more compatible with
how Livestatus works.

Accept more whitespace in request

---

lmd/response.go

After a recent update to the unparam tool it started reporting a couple
of new errors in response.go. This commit addresses those errors to make
unparam happy again.
The change in unparam that introduced the errors can be seen here:
https://github.com/mvdan/unparam/commit/229ad68a599e2622cf9d3bb87a385b158efe736f

Fix failing unparam tests

---

lmd/a_helper_test.go
lmd/nodes_test.go
lmd/request_test.go

Previously, when generating the host and service dataset, only the last
host/service defined in the test data would be used.
This commit ensures that we use the actual dataset, and if more hosts or
services than defined are needed, then we duplicate the last defined
test object (as before).
Given that the test dataset used have changed, a bunch of the expected
values in the tests needed to be adjusted.

Use more of the test dataset

---

lmd/objects.go
lmd/peer.go
lmd/response.go

This commit adds three columns to the host table, services,
services_with_info and services_with_state which is supported in livestatus but
not included in LMD.

Add service info columns to the host table

---

lmd/objects.go
lmd/peer.go
lmd/response.go

This reverts commit a9525f1243ad7f9f3a5e25424c0f60d1a12e5cf8 (which reverts the service info columns commit).
The actually issue we had was not related to this commit, but due to
incompatibilities between our naemon-livestatus and LMD (dependency columns). Therefore this
commit can safely be included again.
Apologies for the confusion.

Revert "Revert "Add service info columns to the host table (#58)" (#60)"

---

lmd/objects.go
lmd/peer.go
lmd/response.go

This PR adds the comments_with_info column to host and services.
Also the host_comments_with_info is added to all the relevant tables. I didn't manage to figure out a good way to have this value "inherited" down, with the rest of the host fields (using AddRefColumn). Instead they are explicitly added to each relevant table.

Comments with info

---

lmd/peer.go

If a host does not have any services, services_with_state and
services_with_info LMD currently returns `null`. Livestatus on the otherhand
returns an empty list instead.
This commit makes the output consistent with livestatus.

Services_with_* should return empty list if empty

---

lmd/request.go
lmd/request_test.go

Sending a command with an incorrect timestamp hang LMD. This patch make it reject the command

correct LMD hang with incorrect COMMAND timestamp

---

lmd/objects.go

The members column of servicegroups where previously defined as a
`StringListCol`. This resulted in an incorrect format, where it would be
impossible to distinguish the hostname from the service description if
either had a space in it.
Livestatus would output the member as: `["monitor","System load average"]`
whereas it would LMD would output it as: `"[monitor System load average]"`
By setting the servicegroup members column to `InterfaceListCol` we
correct the output to be in line with Livestatus.

Change servicegroups members to InterfaceList

---

lmd/filter.go
lmd/request_test.go

Livestatus supports querying column names by prefixing the <table>_ with
the plural s removed. This commit adds support for this in LMD as well.

Add support column name: <table>_<colum-name>

---

lmd/column.go
lmd/datarow.go
lmd/objects.go
lmd/request_test.go

This commit adds the virtual column members_with_state to the hostgroup
and servicegroup tables, as supported by Livestatus.

Add members_with_state column to group tables

---

lmd/objects.go

The days column in the timeperiods table was incorrectly marked as
StringListCol, resulting in LMD formatting the data incorrectly.
LMD would return:
["[]","[28800 61200]","[28800 61200]","[28800 61200]","[28800 61200]"...
Livestatus would return:
[[],[28800,61200],[28800,61200],[28800,61200],[28800,61200],[28800,61200],[]]

Set days column in Timeperiods to InterfaceListCol

---

lmd/datarow.go

As the days column in the timeperiods table is now an InterfaceListCol
we need to re-add support for the type for incoming data.

Re-add InterfaceListCol for incoming data

---

lmd/objects.go

The exceptions in the timeperiods table were incorrectly formatted in
LMD due to the type incorrectly being set to StringListCol. This commit
changes the type to InterfaceListCol which brings the output back in
line with Livestatus.
LMD output prior to this patch:
[["map[swday:0 swday_offset:1 ewday:0 ewday_offset:1 skip_interval:0 ...
Livestatus output:
[[{"swday":0,"swday_offset":1,"ewday":0,"ewday_offset":1,"skip_interval":0 ...

Change exceptions columns to InterfaceListCol

---

.golangci.yml
lmd/a_helper_test.go
lmd/peer.go
lmd/request.go
lmd/request_test.go

This commit adds support for the Negate header. This can be used
together with filters to provide a negated filter result.

Add support for Negate header

---

lmd/datarow.go
lmd/filter.go
lmd/peer.go
lmd/request.go
lmd/request_test.go

Previously if the negate header was included, the whole filter result
would be negated. However in some queries only part of the filter should
be negated, for example:
GET hosts
Filter: alias ~ test
Filter: state = 0
Negate:
And: 2
In this case, we would negate the full query, whereas in Livestatus
only the state filter would be negated.
This commit brings the behavior in line with Livestatus.

Correctly handle negate header in filter groups

---

.golangci.yml
lmd/listener.go
lmd/main.go
lmd/nodes.go
lmd/peer_test.go
lmd/response.go
lmd/resultset.go

This fixed building with golangci-lint 1.18.0, by removing some
whitespaces and allowing bigger functions.
Signed-off-by: Jacob Hansen <jhansen@itrsgroup.com>

Fixes for passing golangci-lint 1.18.0

---

.golangci.yml
lmd/column.go

* Gocognit was recently introduced to golangci-lint. The default limit was
set to 0 causing issues. Set it to 35 to ensure our checks pass.
* disable interfacer
* fix a unused parameter issue

Ensure building with latest golangci-lint works

---

.golangci.yml

The Whitespace linter was failing in multiple places. Disable it for
LMD.
Signed-off-by: Jacob Hansen <jhansen@itrsgroup.com>

Disable wsl linter

---

lmd/peer.go

The comment and downtime cache broke after the recent change increasing
the int size of the ids from 32 to 64. This manifested in issues when
querying comments_with_info for example.
This comments fixes the datatype to int64 in the comment and downtimes
cache as well.
Signed-off-by: Jacob Hansen <jhansen@itrsgroup.com>

Fix comment/downtime cache after int64 change

---

lmd/datarow.go
lmd/request_test.go

The services_with_info plugin_output incorrectly used the hosts
plugin_output rather the the services plugin_output.
Also add a test case for this column.

Correct plugin_output on services_with_info

---

Makefile

With this commit we allow setting a custom build version when invoking
make. For example:
`make BUILD=vendor-build-version`

Allow setting custom build version

---

go.mod
lmd/listener.go
lmd/request.go

When a EOF is sent, LMD did not correctly terminate KeepAlive sessions.
However no more queries would be answered after an EOF. This resulted in
the KeepAlive connection hanging unnecessarily.

Break keep alive connection on EOF

---

Makefile

It seems that running `go mod tidy` generates vendor changes, which
could lead to build problems. Re-ordering `go mod vendor` and `go mod
tidy` fixes this.

Re-order `go mod vendor` and `go mod tidy`

---

lmd/datastore.go

When pre-filtering services by host name the services are fetched as map
and then converted to an array. Since maps are an unordered
data structure the order of the resulting array will essentially be
random. This causes an issue with service queries which follow the
default sort order, the result of these queries are not sorted because
they are expected to already be sorted. So for a simple service query
in the default sort order with a host_name filter which triggers
pre-filtering this combination produces a result where the order of the
services is random.
With this commit the services are sorted by their description, which is
the default order, before returning them in the pre-filtering stage.
Signed-off-by: Erik Sjöström <esjostrom@itrsgroup.com>

Keep services sorted after indexing

---

lmd/objects.go
t/data/contacts.json

Naemon defines six optional fields for additional address information,
named `address1`, `adress2`, up to `address6`. This commit adds those
six fields to LMD, so that they can be queried for. This aligns the
behavior of LMD with that of Livestatus.
Signed-off-by: Petter Nyström <pnystrom@itrsgroup.com>

Add address1 to address6 fields to contacts

---

lmd.ini.example
lmd/logging.go

This is a very naive attempt at making the log output configurable to not output colors, and skip the date/time, since these would be provided by journald anyway.
I'm pretty sure that this is not the optimal way to implement it, but I wanted to run this in production (I'm currently setting up a local lmd on each of our worker processes, to replace the xinetd-alike unixcat approach of accessing the livestatus unix socket via tcp/ip). In our production environment we use filebeat to transport the journal to a central instance, and I wanted to avoid having to strip ansi-escape-sequences in filebeat.
The better approach probably needs more config options to enable/disable datetime logging and colors separately from each other, or autodetects if the output goes to a terminal to enable colors …

introduce logfile "stdout-journal"

---

lmd/request.go
lmd/request_test.go

I needed to make a few minor changes to allow CheckMK to use lmd as a livestatus source.
CheckMK uses `OutputFormat: python3` and these tiny changes seemed to do the trick. It seems to work with these changes applied.
That said, I am obviously slightly curious as to why I didn't need to perform any actual modifications to the data, but there you have it.
Please let me know if I'm missing something glaringly obvious. :)

Accept "python3" OutputFormat
